name: Build and Deploy

on:
  push:
    branches: [ main, MELOSYS-7468 ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: melosys
          POSTGRES_USER: melosys
          POSTGRES_DB: melosys_skjema
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - name: Run tests
        run: ./gradlew test
        env:
          DB_USERNAME: melosys
          DB_PASSWORD: melosys

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/MELOSYS-7468'
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: melosys
          POSTGRES_USER: melosys
          POSTGRES_DB: melosys_skjema
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - name: Build application
        run: ./gradlew build
        env:
          DB_USERNAME: melosys
          DB_PASSWORD: melosys
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: melosys
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/MELOSYS-7468'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/application.yml
          VAR: image=${{ needs.build.outputs.image }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/application.yml
          VAR: image=${{ needs.build.outputs.image }}