name: Build and deploy
on:
  push:
    branches:
      - MELOSYS-7468
jobs:
  build_and_deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: melosys
          POSTGRES_USER: melosys
          POSTGRES_DB: melosys_skjema
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for what-changed action
      - name: Determine what to do
        id: changed-files
        uses: "nais/what-changed@main"
        with:
          files: .nais/app.yaml #, topic.yaml, statefulset.yaml, etc.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build application
        run: ./gradlew build
        env:
          DB_USERNAME: melosys
          DB_PASSWORD: melosys
      - name: Build and push image and SBOM to OCI registry
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teammelosys
      - name: Deploy to Nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }}, spring_profile=dev